# Generated by Django 3.2.9 on 2021-12-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='<django.db.models.fields.related.ForeignKey>/documents/<django.db.models.fields.CharField>')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.user')),
            ],
        ),
    ]
