# Generated by Django 3.2.9 on 2021-12-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_document'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
    ]
