# Generated by Django 3.2.9 on 2021-12-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='Main/documents/'),
        ),
    ]
