# Generated by Django 3.2.9 on 2021-12-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='static/Main/documents/'),
        ),
    ]
