# Generated by Django 3.2.9 on 2021-12-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_document_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
